### ISSUE TITLE
LTTng ref trace with channel filenames like chan1_0 does load

### ISSUE THREAD

**Issue by ivberg** [microsoft/Microsoft-Performance-Tools-Linux#12]
I am new to CTF. I have found from a LTTNG tutorial a sample file https://lttng.org/blog/2018/03/21/lttng-scope-0.3-a-basic-tutorial/ which has a tarball of https://github.com/lttng/lttng-ref-traces/raw/master/traces/basic-kernel-analysis.tar.xz
The trace data generated by lttng is a folder of channel files 
![image](https://user-images.githubusercontent.com/408821/109808970-0d621580-7c28-11eb-871d-631280161681.png)

To make it ctf it is sufficient to zip the complete folder, rename to ctf and load it in WPA? I have tried that but I get then 

```
Unable to process 'file:///C:/basic-kernel-analysis/kernel.ctf': System.Exception: No events - failure processing .ctf
   at PerfCds.PerfSourceParser.ProcessSource(ISourceDataProcessor`3 dataProcessor, ILogger logger, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\1\s\Microsoft-Performance-Tools-Linux\PerfCds\PerfSourceParser.cs:line 132
   at Microsoft.Performance.SDK.Runtime.Extensibility.SourceProcessingSession`3.ProcessSource(ILogger logger, IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBaseWithSourceParser`3.ProcessAsyncCore(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBase.ProcessAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Runtime.CustomDataSourceExecutor.ExecuteAsync(CancellationToken cancellationToken)
Unable to process 'file:///C:/basic-kernel-analysis/kernel.ctf': System.Exception: No events - failure processing .ctf
   at LTTngCds.LTTngSourceParser.ProcessSource(ISourceDataProcessor`3 dataProcessor, ILogger logger, IProgress`1 progress, CancellationToken cancellationToken) in D:\a\1\s\Microsoft-Performance-Tools-Linux\LTTngCds\LTTngSourceParser.cs:line 135
   at Microsoft.Performance.SDK.Runtime.Extensibility.SourceProcessingSession`3.ProcessSource(ILogger logger, IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBaseWithSourceParser`3.ProcessAsyncCore(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Processing.CustomDataProcessorBase.ProcessAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.Performance.SDK.Runtime.CustomDataSourceExecutor.ExecuteAsync(CancellationToken cancellationToken)
Unable to process any data sources.
```

I have copied the extensions of your drop to "C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\CustomDataSources\MicrosoftPerfToolkitAddins". WPA comes then up properly.

_Originally posted by @Alois-xx in https://github.com/microsoft/Microsoft-Performance-Tools-Linux/issues/6#issuecomment-789695784_

**Comment by ivberg** [comment]
Working on fixed. Will send PR @Alois-xx
